import { defineConfig } from 'vite';
import tailwindcss from '@tailwindcss/vite';

// Production-optimized configuration for maximum tree shaking and minimal bundle size
export default defineConfig({
  plugins: [tailwindcss()],
  build: {
    outDir: 'dist',
    sourcemap: false,
    assetsDir: '',
    minify: 'terser',
    cssCodeSplit: false, // Inline CSS for widgets
    cssMinify: 'esbuild',
    target: 'es2020',
    lib: false,
    rollupOptions: {
      input: {
        widget: './src/widget/index.tsx',
        'widget-iframe': './src/widget/index-iframe.tsx',
      },
      output: {
        entryFileNames: '[name].js',
        assetFileNames: '[name].css',
        manualChunks: undefined,
        compact: true,
        generatedCode: {
          arrowFunctions: true,
          constBindings: true,
          objectShorthand: true,
        },
      },
      treeshake: {
        moduleSideEffects: false,
        propertyReadSideEffects: false,
        tryCatchDeoptimization: false,
        preset: 'smallest',
      },
      external: [],
    },
    terserOptions: {
      ecma: 2020,
      module: true,
      toplevel: true,
      compress: {
        arguments: true,
        arrows: true,
        booleans: true,
        collapse_vars: true,
        comparisons: true,
        computed_props: true,
        conditionals: true,
        dead_code: true,
        directives: true,
        drop_console: true,
        drop_debugger: true,
        evaluate: true,
        expression: true,
        hoist_funs: true,
        hoist_props: true,
        hoist_vars: false,
        if_return: true,
        inline: true,
        join_vars: true,
        keep_fargs: false,
        loops: true,
        module: true,
        negate_iife: true,
        passes: 5, // More passes for maximum optimization
        properties: true,
        pure_funcs: [
          'console.log',
          'console.info',
          'console.debug',
          'console.warn',
          'console.error',
          'console.trace',
          'console.time',
          'console.timeEnd',
        ],
        pure_getters: true,
        reduce_funcs: true,
        reduce_vars: true,
        sequences: true,
        side_effects: false,
        switches: true,
        toplevel: true,
        typeofs: true,
        unsafe: true,
        unsafe_arrows: true,
        unsafe_comps: true,
        unsafe_Function: true,
        unsafe_math: true,
        unsafe_symbols: true,
        unsafe_methods: true,
        unsafe_proto: true,
        unsafe_regexp: true,
        unsafe_undefined: true,
        unused: true,
      },
      mangle: {
        toplevel: true,
        eval: true,
        keep_fnames: false,
        properties: {
          regex: /^_/,
        },
      },
      format: {
        comments: false,
        ecma: 2020,
        ascii_only: true,
      },
    },
    reportCompressedSize: true,
    chunkSizeWarningLimit: 300, // Stricter limit for widgets
  },
  esbuild: {
    legalComments: 'none',
    treeShaking: true,
    minifyIdentifiers: true,
    minifySyntax: true,
    minifyWhitespace: true,
    drop: ['console', 'debugger'],
    target: 'es2020',
  },
  define: {
    __DEV__: false,
    'process.env.NODE_ENV': '"production"',
    'import.meta.env.DEV': false,
    'import.meta.env.PROD': true,
  },
  optimizeDeps: {
    include: ['react', 'react-dom'],
    exclude: [],
  },
});
